Internal Server Error: /accounts/promote-to-superuser/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/views.py", line 181, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/serializers.py", line 118, in validate
    value = value.lower().strip()
            ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lower'
"POST /accounts/promote-to-superuser/ HTTP/1.1" 500 113600
Internal Server Error: /accounts/promote-to-superuser/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/views.py", line 181, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/serializers.py", line 118, in validate
    value = value.strip()
            ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'strip'
"POST /accounts/promote-to-superuser/ HTTP/1.1" 500 113584
Internal Server Error: /accounts/promote-to-superuser/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/views.py", line 181, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/serializers.py", line 118, in validate
    value = str(value.lower().strip())
                ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lower'
"POST /accounts/promote-to-superuser/ HTTP/1.1" 500 113618
Internal Server Error: /accounts/promote-to-superuser/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/views.py", line 181, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/serializers.py", line 118, in validate
    value = value.lower().strip()
            ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lower'
"POST /accounts/promote-to-superuser/ HTTP/1.1" 500 113605
