Internal Server Error: /accounts/promote-to-superuser/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/views.py", line 181, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/serializers.py", line 118, in validate
    value = value.lower().strip()
            ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lower'
"POST /accounts/promote-to-superuser/ HTTP/1.1" 500 113600
Internal Server Error: /accounts/promote-to-superuser/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/views.py", line 181, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/serializers.py", line 118, in validate
    value = value.strip()
            ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'strip'
"POST /accounts/promote-to-superuser/ HTTP/1.1" 500 113584
Internal Server Error: /accounts/promote-to-superuser/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/views.py", line 181, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/serializers.py", line 118, in validate
    value = str(value.lower().strip())
                ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lower'
"POST /accounts/promote-to-superuser/ HTTP/1.1" 500 113618
Internal Server Error: /accounts/promote-to-superuser/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/views.py", line 181, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/serializers.py", line 118, in validate
    value = value.lower().strip()
            ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lower'
"POST /accounts/promote-to-superuser/ HTTP/1.1" 500 113605
Internal Server Error: /blogs/add-category
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/blogs/add-category/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
"POST /blogs/add-category HTTP/1.1" 500 78236
